name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: cache gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
      - name: generate google-services.json from environment variables
        run: echo $GOOGLE_SERVICES_JSON | base64 --decode > ${GITHUB_WORKSPACE}/app/google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      - name: Lint
        run: ./gradlew lint
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: cache gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
      - name: generate google-services.json from environment variables
        run: echo $GOOGLE_SERVICES_JSON | base64 --decode > ${GITHUB_WORKSPACE}/app/google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      - name: Build with Gradle
        run: ./gradlew build

      - name: Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          script: ./gradlew jacocoTestReport

      - uses: actions/upload-artifact@v2
        with:
          name: report
          path: ./app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: report
          path: ./
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./jacocoTestReport.xml
          flags: unittests
          fail_ci_if_error: true

