name: Android CI

on: [push]

jobs:
  build:
    name: Build & Test
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: cache gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: generate google-services.json from environment variables
        run: echo $GOOGLE_SERVICES_JSON | base64 --decode > ${GITHUB_WORKSPACE}/app/google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

      - name: Build with Gradle
        run: ./gradlew build

      - name: Lint
        run: ./gradlew lint

      - name: Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          script: ./gradlew jacocoTestReport

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
          flags: unittests
          fail_ci_if_error: true


  notify:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Slack notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        uses: Ilshidur/action-slack@master
        with:
          args: 'A new commit has been pushed.'

